variables:
    TWINE_USERNAME: SECURE
    TWINE_PASSWORD: SECURE
    TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/
    PYBIN: /opt/python/cp35-cp35m/bin

stages:
    - deploy
    - web

build:
    image: "quay.io/pypa/manylinux2010_x86_64"
    stage: deploy
    
    # install SWIG
    before_script:
        - yum -y -q update
        - yum install -y -q https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        - yum -y -q groupinstall "Development Tools"
        - yum -y -q --enablerepo=extras install epel-release
        - yum install -y -q bison flex git centos-release-scl
        - yum install -y -q wget curl
        - yum install -y -q automake autoconf pcre-devel
        - yum -y -q update
        - /opt/python/cp35-cp35m/bin/pip install -U setuptools wheel twine auditwheel
        #- /opt/python/cp35-cp35m/bin/pip install -U anybadge
        - git clone https://github.com/swig/swig.git
        - cd swig
        - git checkout rel-4.0.0
        - ./autogen.sh
        - ./configure
        - make
        - make install
        - cd ..
        - git clone https://github.com/m7thon/doxy2swig
        - mv doxy2swig/doxy2swig.py .
        - /opt/python/cp35-cp35m/bin/pip install -U pdoc3
        
        
    # compile libcolgraph and copy status (build.svg) to public/
    script:
        - make docs
        - /opt/python/cp35-cp35m/bin/python setup.py sdist bdist_wheel
        - auditwheel repair dist/*.whl -w dist
        - /opt/python/cp35-cp35m/bin/python -m twine upload dist/*.tar.gz  --verbose
        - /opt/python/cp35-cp35m/bin/python -m twine upload dist/*manylinux*.whl --verbose
        #- if /opt/python/cp35-cp35m/bin/python -m twine upload dist/*.tar.gz  --verbose && /opt/python/cp35-cp35m/bin/python -m twine upload dist/*manylinux*.whl --verbose; then echo "PASSED JOB" && /opt/python/cp35-cp35m/bin/python -m anybadge --label=pipeline --value=passing --file=build.svg passing=green failing=red; else echo "FAILED JOB" && /opt/python/cp35-cp35m/bin/python -m anybadge --label=pipeline --value=failing --file=build.svg passing=green  failing=red; fi
        #- mkdir -p public; mv build.svg public/build.svg
        
    after_script:
        - mkdir -p public/static
        - cp libcolgraph/web/static/favicon.ico public/static
        - make
        - cat requirements.txt | xargs -n 1 /opt/python/cp35-cp35m/bin/pip install
        - /opt/python/cp35-cp35m/bin/python -m libcolgraph.web -p 5000 &
        - wget -r -np -k http://localhost:5000
        - mv localhost*/* public/demo/
        
    artifacts:
        paths:
            - public/
            - build/
            - dist/
            - docs/
            - libcolgraph.egg-info/
            - setup.py
            - requirements.txt
    only:
        refs:
            - master
        changes:
            - .pipeline.trigger
    allow_failure: false
    environment:
        name: dev


pages:
    stage: web
    dependencies:
        - build
    script:
        - mkdir -p public
        #- mv public/index.txt public/index.html
    artifacts:
        paths:
            - public/
    only:
        refs:
            - master
        changes:
            - .pipeline.trigger

